def build(bld):
    simple = bld.create_ns3_program('ndnfd-simple', ['NDNFD'])
    simple.source = 'ndnfd-simple.cc'

    migration = bld.create_ns3_program('ndnfd-migration', ['NDNFD'])
    migration.source = 'ndnfd-migration.cc'

    multipath = bld.create_ns3_program('ndnfd-multipath', ['NDNFD'])
    multipath.source = 'ndnfd-multipath.cc'

    fattree = bld.create_ns3_program('ndnfd-fattree', ['NDNFD'])
    fattree.source = 'ndnfd-fattree.cc'

    producer_throttled = bld.create_ns3_program('ndnfd-producer-throttled', ['NDNFD'])
    producer_throttled.source = 'ndnfd-producer-throttled.cc'

    loadbal_csma = bld.create_ns3_program('ndnfd-loadbal-csma', ['NDNFD'])
    loadbal_csma.source = 'ndnfd-loadbal-csma.cc'

