def build(bld):
    simple = bld.create_ns3_program('ndnfd-simple', ['NDNFD'])
    simple.source = 'ndnfd-simple.cc'

    sl_failover = bld.create_ns3_program('ndnfd-selflearn-failover', ['NDNFD'])
    sl_failover.source = 'ndnfd-selflearn-failover.cc'

    sl_multipath = bld.create_ns3_program('ndnfd-selflearn-multipath', ['NDNFD'])
    sl_multipath.source = 'ndnfd-selflearn-multipath.cc'

    sl_fattree = bld.create_ns3_program('ndnfd-selflearn-fattree', ['NDNFD'])
    sl_fattree.source = 'ndnfd-selflearn-fattree.cc'

    sl_producer_throttled = bld.create_ns3_program('ndnfd-producer-throttled', ['NDNFD'])
    sl_producer_throttled.source = 'ndnfd-producer-throttled.cc'


